language: python

sudo: false

python:
  - "3.4.2"

install:
  - pip install pytest pytest-cov coverage==3.7.1 coveralls==1.1

script:
  - py.test --cov

after_success:
  - CI=true TRAVIS=true coveralls
